api/urls.py
from django.contrib.staticfiles.urls import urlpatterns
from django.urls import path
from django.urls.conf import include
from django.urls.resolvers import URLPattern
from rest_framework import routers
from .views import CourseViewSet, StudentViewSet, TrainerViewSet
from rest_framework_swagger.views import get_swagger_view
router = routers.DefaultRouter()
router.register(r'students', StudentViewSet),
router.register(r'trainers',TrainerViewSet),
router.register(r'courses', CourseViewSet),

schema_view = get_swagger_view(title='School management API')


urlpatterns = [
    path('^$', schema_view),
    path('',include(router.urls)),
]

school_system/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from rest_framework.schemas import get_schema_view
from django.views.generic import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls', namespace="student")),
    path('trainers/', include('trainer.urls', namespace="trainer")),
    path('courses/',include('course.urls', namespace="course")),
    path('events/',include('event.urls')),
    path('all/', include('api.urls')),
    path('openapi/', get_schema_view(title="School Management System",description="School Management System"), name='openapi-schema'),
    path('docs/', TemplateView.as_view(template_name='documentation.html',extra_context={'schema_url':'openapi-schema'}), name='swagger-ui'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainer/urls.py
from django.urls import path
from .views import TrainerList, TrainersFormView, delete_trainer, edit_trainer,  trainer_profile
from . import views 
app_name = "trainer"

urlpatterns =[
    path ('', TrainerList.as_view(), name='trainer'),
    path ('add_trainer/',TrainersFormView.as_view(), name='add_trainer'),
    path ('<id>/delete', delete_trainer, name = 'delete_trainer'),
    path('<id>/edit',edit_trainer, name='edit_trainer'),
    path('<id>/view',trainer_profile, name='trainer_profile'),
]

trainer/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.
class Trainer(models.Model):
    first_name = models.CharField(max_length=15)
    second_name = models.CharField(max_length=15)
    company = models.CharField(max_length=25)
    course_name = models.CharField(max_length=20)
    course = models.IntegerField()
    email = models.EmailField()
    joining_date = models.DateField()
    salary = models.BigIntegerField()
    city = models.CharField(max_length=20)
    image = models.ImageField(upload_to='images/')
    resume = models.FileField()
    contract = models.FileField()
    phone_number = PhoneNumberField(unique = True, null = False, blank = False)
    gender = (
        ('m', 'male'),
        ('f', 'female')
    )

    def __str__(self):
        return self.first_name

trainer/forms.py
from django import forms
from django.db.models import fields
from .models import Trainer


class TrainerForm(forms.ModelForm):

    class Meta:
        model = Trainer
        fields = '__all__'

trainer/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render , redirect
from django.views.generic.edit import CreateView
from .models import Trainer
from django.views.generic import ListView
from .forms import TrainerForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

# Create your views here.



class TrainerList(ListView):
    model = Trainer
    template_name = 'trainers_list.html'

    def get_queryset(self, *args, **kwargs):
        all_trainers = super(TrainerList, self).get_queryset(*args, **kwargs)
        return all_trainers

class TrainersFormView(CreateView):
    form_class =  TrainerForm
    model = Trainer
    template_name = 'add_trainer.html'
    success_url =reverse_lazy('trainer:trainer')

def delete_trainer(request, id):
    trainer = Trainer.objects.get(id = id)

    if request.method == "POST":
        trainer.delete()
        return redirect("/trainers/")
    return render(request, 'delete_trainer.html', {'trainer': trainer})

def edit_trainer(request, id):
    context = {}

    trainer= Trainer.objects.get( id = id)
    form =TrainerForm(request.POST or None, instance = trainer)


    if form.is_valid():
        form.save()
        return redirect("/trainers/")
    context["form"] = form

    return render(request, "edit_trainer.html", context)


def trainer_profile(request, id):
    trainer = Trainer.objects.get(id = id)
    return render (request, 'trainer_profile.html', {'trainer': trainer})

trainer/templates/add_trainer.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
<!Doctype html>
<html>
    <head>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


    </head>
    {% block body%}
    <body>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>





<div class="check">
<h2>Add Trainer Form</h2>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
       
        <button type="submit" class="save btn btn-success">Save</button>
    </form>
</div>
<style>
    .check{
        height:50%;
        width:25%;
        padding-left:80px; 
    }
    h2{
        background-color: chartreuse;
    }
    </style>
</style>


    </body>
    {% endblock body%}
    </html>

trainer/templates/delete_trainer.html
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you want to delete {{trainer.first_name}} ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
        
    </form>
    <style>
        .main{
            font-size: medium;
            font-family: Verdana, Arial, Helvetica, sans-serif;

            text-align: center;
        }

       input{
           background-color:limegreen
       }
    </style>
</div>

trainer/templates/edit_trainer.html
<div class="form-row">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
 
        <!-- form as paragraph -->
        {{ form.as_p }}
 
        <input type="submit" value="Update">
    </form>
 
</div>

trainer/templates/trainer_profile.html
{{trainer.first_name}}
{{trainer.last_name}}

{{trainer.email}}

<img src="{{ trainer.image.url }}"width="100" height="100"/>

trainer/templates/trainers_list.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>School Management System</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

{% block body %}

<body>

{%block content%}

<div class="container">
  <h2>Registered Trainers List</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">First Name</th>
        <th scope="col">Second Name</th>
        <th scope="col">Course Name</th>
        <th scope="col">Course Code</th>
        <th scope="col">Email</th>
        <th scope="col">Image</th>
       
      </tr>
    </thead>
 
    <tbody>
      {% for trainer in trainer_list%} 

      <tr>

        <td>{{trainer.first_name}}</td>
        <td>{{trainer.last_name}}</td>
     
        <td>{{trainer.course_name}}</td>
    
        <td>{{trainer.course}}</td>
       
        <td>{{trainer.email}}</td>
       
       <td><img  src="{{ trainer.image.url }}"width="100" height="100"/></td>
     

        <td><a href ="{{trainer.id}}/delete"><button type="submit" class="save btn btn-danger">Delete</button></td></a>
        <td><a href ="{{trainer.id}}/edit"><button type="submit" class="save btn btn-success">Edit</button></td></a>
        <td><a href ="{{trainer.id}}/view"><button type="submit" class="save btn btn-info">Profile</button></td></a>


      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>

 {%endblock content%}             
</body>

<style>
  h2{
    text-align: center;
  }
</style>
</html>
{%endblock body%}