api/urls.py
from django.contrib.staticfiles.urls import urlpatterns
from django.urls import path
from django.urls.conf import include
from django.urls.resolvers import URLPattern
from rest_framework import routers
from .views import CourseViewSet, StudentViewSet, TrainerViewSet
from rest_framework_swagger.views import get_swagger_view
router = routers.DefaultRouter()
router.register(r'students', StudentViewSet),
router.register(r'trainers',TrainerViewSet),
router.register(r'courses', CourseViewSet),

schema_view = get_swagger_view(title='School management API')


urlpatterns = [
    path('^$', schema_view),
    path('',include(router.urls)),
]

course/urls.py
from django.urls import path
from .models import Course
from .views import CoursesFormView, CoursesList, delete_course, edit_course, view_course
app_name = "course"
urlpatterns = [
    path('', CoursesList.as_view(),name ="course"),
    path ('add_course', CoursesFormView.as_view(),name='add_course'),
    path('<id>/delete',delete_course, name='delete_student'),
    path('<id>/edit',edit_course, name='edit_course'),
    path('<id>/view',view_course, name='view_profile' )
]

school_system/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from rest_framework.schemas import get_schema_view
from django.views.generic import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls', namespace="student")),
    path('trainers/', include('trainer.urls', namespace="trainer")),
    path('courses/',include('course.urls', namespace="course")),
    path('events/',include('event.urls')),
    path('all/', include('api.urls')),
    path('openapi/', get_schema_view(title="School Management System",description="School Management System"), name='openapi-schema'),
    path('docs/', TemplateView.as_view(template_name='documentation.html',extra_context={'schema_url':'openapi-schema'}), name='swagger-ui'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from . import views
from .views import StudentList, StudentFormView, delete_student, edit_student, student_profile,home
app_name = "student"

urlpatterns = [
    path('', home, name='home'),
    path('students',StudentList.as_view() , name='student'),
    path('add_student/',StudentFormView.as_view(), name='add_students'),
    path('<id>/delete',delete_student,name='delete_student'),
    path('<id>/edit',edit_student,name='edit_student'),
    path('<id>/view',student_profile, name='student_profile'),

]

trainer/urls.py
from django.urls import path
from .views import TrainerList, TrainersFormView, delete_trainer, edit_trainer,  trainer_profile
from . import views 
app_name = "trainer"

urlpatterns =[
    path ('', TrainerList.as_view(), name='trainer'),
    path ('add_trainer/',TrainersFormView.as_view(), name='add_trainer'),
    path ('<id>/delete', delete_trainer, name = 'delete_trainer'),
    path('<id>/edit',edit_trainer, name='edit_trainer'),
    path('<id>/view',trainer_profile, name='trainer_profile'),
]

student/models.py
from django.db import models
from django.db.models.fields import CharField
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
GENDERS_CHOICES= (
        ("m", "male"),
        ("f", "female")
    )
class Student(models.Model):
    
    first_name = models.CharField(max_length=15,help_text="Stores first name of student")
    last_name = models.CharField(max_length=15)
    age = models.PositiveSmallIntegerField()
    nationality = models.CharField(max_length=20)
    date_of_birth = models.DateField()
    class_name = models.CharField(max_length=20)
    nationality_id = models.CharField(max_length=15)
    email = models.EmailField()
    admission_date = models.DateField()
    academic_year = models.IntegerField()
    image = models.ImageField(upload_to='images/')
    guardians_contact = PhoneNumberField(unique = True, null = False, blank = False)
    student_contact = PhoneNumberField(unique = True, null = False, blank = False)
    room = models.CharField(max_length=20)
    gender =models.CharField(max_length=10,choices=GENDERS_CHOICES,default='female')
  
    

    def __str__(self):
        return self.first_name

student/forms.py
from django import forms
from django.db.models import fields
from .models import Student
class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

student/views.py
from django.http import request
from django.shortcuts import redirect, render
from .models import Student
from .forms import StudentForm
from django.views.generic.list import ListView 
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.shortcuts import (get_list_or_404,HttpResponseRedirect)
from django.views.generic.edit import UpdateView
from trainer.models import Trainer
from course.models import Course


def home(request):
    data = []
    total_students = Student.objects.all().count()
    total_trainers =Trainer.objects.all().count() 
    total_courses = Course.objects.all().count()
    data.append([total_students,total_trainers, total_courses])
    
    return render (request, 'navbar.html', {'top_data':data})




#viewing all the students
class StudentList(ListView):
    model = Student
    template_name = 'students_list.html'

    def get_queryset(self, *args, **kwargs):
        all_students = super(StudentList, self).get_queryset(*args, **kwargs)
        return all_students
       
#registering a new student
class StudentFormView(CreateView):
    template_name = 'add_student.html'
    form_class = StudentForm
    model = Student
    success_url = reverse_lazy('student:student')

  #deleting a student
def delete_student(request, id):
    student= Student.objects.get( id = id)
   
    if request.method =="POST":
       student.delete()
       return HttpResponseRedirect("/students")
    return render(request, 'delete_student.html', {'student':student})

#editing student details
def edit_student(request, id):
    context = {}

    student= Student.objects.get( id = id)
    form =StudentForm(request.POST or None, instance = student)


    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/")
    context["form"] = form

    return render(request, "edit_student.html", context)

def student_profile(request, id):
    student = Student.objects.get(id=id)
    return render(request,'student_profile.html',{'student':student})

student/templates/add_student.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
<!Doctype html>
<html>
    <head>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


    </head>
    {% block body%}
    <body>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>





<div class="check">
<h2>Add Student Form</h2>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
       
        <button type="submit" class="save btn btn-success">Save</button>
    </form>
</div>
<style>
    .check{
        height:50%;
        width:25%;
        padding-left:80px; 
    }
    h2{
        background-color: chartreuse;
    }
    </style>
</style>


    </body>
    {% endblock body %}
        
    </body> }
    </html>

student/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- SOCIAL MEDIA META -->
    <meta property="og:description" content="Nepal Drone Portal">
    <meta property="og:image" content="preview.html">
    <meta property="og:site_name" content="Nepal Drone Portal">
    <meta property="og:title" content="Nepal Drone Portal">
    <meta property="og:type" content="website">
    <meta property="og:url" content="http://naxa.com.np">

    <!-- TWITTER META -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@Nepal Drone Portal">
    <meta name="twitter:creator" content="@Nepal Drone Portal">
    <meta name="twitter:title" content="Nepal Drone Portal">
    <meta name="twitter:description" content="Nepal Drone Portal">
    <meta name="twitter:image" content="preview.html">

    <!--title-->
    <title>School Management System</title>

    <!-- faveicon start   -->
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" sizes="32x32">

    <!-- stylesheet start -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'datatable/datatables.min.css' %}" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css"></link>
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css"></link>

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block links %}

    {% endblock links %}

</head>

<body class="">
    <div class="body-container">
        <div class="drone-admin-wrapper">
            {% include 'navbar.html' %}
            {% block body %}

            {% endblock body %}
        </div>
    </div>

    <!-- Jquery Core Js -->
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/Leaflet.fullscreen.min.js'></script>

    <script src="{% static 'js/leaflet.ajax.min.js' %}"></script>
    <script src="{% static 'js/map.js' %}"></script>
    <script src="{% static 'datatable/datatables.min.js' %}"></script>
    <script src="{% static 'js/custom-datatable.js' %}"></script>
    <script src="{% static 'js/drone.js' %}"></script>
    <script>
        var csrftoken = '{{ csrf_token }}';
    </script>

    {% block footer_links %}

    {% endblock footer_links %}

</body>


</html>

student/templates/delete_student.html
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you want to delete {{student.first_name}} ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
        
    </form>
    <style>
        .main{
            font-size: medium;
            font-family: Verdana, Arial, Helvetica, sans-serif;

            text-align: center;
        }

       input{
           background-color:limegreen
       }
    </style>
</div>

student/templates/edit_student.html
<div class="form-row">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
 
        <!-- form as paragraph -->
        {{ form.as_p }}
 
        <input type="submit" value="Update">
    </form>
 
</div>

student/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>School Management System</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
{%block body%}
<nav class="navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#"><img src="media/dow.jpeg" class="rounded"></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="act"><a href="{% url 'student:home' %}">Home</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Students<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'student:student' %}">Students List</a></li>
            <li><a href="{% url 'student:add_students' %}">Add Student</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Trainers<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'trainer:trainer' %}">Trainers List</a></li>
            <li><a href="{% url 'trainer:add_trainer' %}">Add Trainer</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Courses<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'course:course' %}">Courses List</a></li>
            <li><a href="{% url 'course:add_course' %}">Add Course</a></li>
          </ul>
        </li>
        
      </ul>
  
    </div>
  </div>
</nav>
<div class="container">
  <ul class="list-group">
    <li class="list-group-item">Registered Students<div class="total-count">
      <h4>{{ top_data.0.0 }}</h4>
  </div></li>
    <li class="list-group-item">Registered Trainers<div class="info-content">
      <div class="total-count">
          <h4>{{ top_data.0.1 }}</h4>
      </div>
  </div></li>
    <li class="list-group-item">Registered Courses<div class="total-count">
      <h4>{{ top_data.0.2 }}</h4>
  </div></li>
  </ul>
</div>


     
</body>

{%endblock body%}

<style>
  img{
    width:40px;
    margin-top: -10px;
  }
  .navbar-inverse{
    background-color: #584059;
  }
  body{
    background-image: url("media/c.webp");
    background-repeat: no-repeat;
    background-size: 750px 600px;
  }
  .drone-info{
    padding-left: 20px
  }
  .container{
    padding-left: 700px;
    padding-top: 120px;
  }
.list-group-item{
  background-color: #f5e6f3;
}




</style>

</html>

student/templates/student_profile.html
{{student.first_name}}
{{student.last_name}}
{{student.age}}
{{student.nationality}}
{{student.date_of_birth}}
{{student.class_name}}
{{student.nationality_id}}
{{student.email}}
{{student.admission_date}}
{{student.academic_year }}
<img src="{{ student.image.url }}"width="100" height="100"/>
{{student.guardians_contact}}
{{student.student_contact}}
{{student.room}}
{{student.gender}}

student/templates/students_list.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>School Management System</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

{% block body %}

<body>


<div class="container">
  <h2>Registered Students List</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Nationality</th>
        <th scope="col">Class Name</th>
        <th scope="col">Email</th>
        <th scope="col">Image</th>
       
      </tr>
    </thead>
 
    <tbody>
      {% for student in student_list%} 

      <tr>

        <td>{{student.first_name}}</td>
        <td>{{student.last_name}}</td>
     
        <td>{{student.nationality}}</td>
    
        <td>{{student.class_name}}</td>
       
        <td>{{student.email}}</td>
       
        <td><img  src="{{ student.image.url }}"width="100" height="100"/></td>
     

        <td><a href ="{{student.id}}/delete"><button type="submit" class="save btn btn-danger">Delete</button></td></a>
        <td><a href ="{{student.id}}/edit"><button type="submit" class="save btn btn-success">Edit</button></td></a>
        <td><a href ="{{student.id}}/view"><button type="submit" class="save btn btn-info">Profile</button></td></a>


      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>

              
</body>
<style>
  h2{
    text-align: center;
  }
</style>
</html>
{%endblock body%}